// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAD8LMjQ1LtBgySVTuvltvmVwY_0qIczSU',
    appId: '1:118052670452:web:3544411af2e6367a8907a1',
    messagingSenderId: '118052670452',
    projectId: 'ecommerce-app-6e21a',
    authDomain: 'ecommerce-app-6e21a.firebaseapp.com',
    storageBucket: 'ecommerce-app-6e21a.firebasestorage.app',
    measurementId: 'G-G4WGHKED4M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgsurEp4EMA7avcdsuKrj0597nQdCIgAs',
    appId: '1:118052670452:android:f9e8ce8b3a2051888907a1',
    messagingSenderId: '118052670452',
    projectId: 'ecommerce-app-6e21a',
    storageBucket: 'ecommerce-app-6e21a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBirvDZrK34-rUtTks5CP9KNPoP5T2j2Iw',
    appId: '1:118052670452:ios:7d929c20ed64c7228907a1',
    messagingSenderId: '118052670452',
    projectId: 'ecommerce-app-6e21a',
    storageBucket: 'ecommerce-app-6e21a.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBirvDZrK34-rUtTks5CP9KNPoP5T2j2Iw',
    appId: '1:118052670452:ios:7d929c20ed64c7228907a1',
    messagingSenderId: '118052670452',
    projectId: 'ecommerce-app-6e21a',
    storageBucket: 'ecommerce-app-6e21a.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAD8LMjQ1LtBgySVTuvltvmVwY_0qIczSU',
    appId: '1:118052670452:web:1afe64220fb9d0728907a1',
    messagingSenderId: '118052670452',
    projectId: 'ecommerce-app-6e21a',
    authDomain: 'ecommerce-app-6e21a.firebaseapp.com',
    storageBucket: 'ecommerce-app-6e21a.firebasestorage.app',
    measurementId: 'G-FRGQW914Q9',
  );
}
